apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: balkani-frontend
  namespace: default
  labels:
    app: balkani-frontend
  annotations:
    # Cert-manager annotations
    acme.cert-manager.io/http01-edit-in-place: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: 'true'

    # Nginx Ingress Controller annotations
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/use-regex: 'true'

    # Additional security headers
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-XSS-Protection: 1; mode=block";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - balkan.codbun.com
    secretName: balkani-frontend-tls
  rules:
  - host: balkan.codbun.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: balkani-frontend
            port:
              number: 80
